name: lfcont
networks:
  0p5dev:
    driver: bridge
    name: 0p5dev
services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: lfcont
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
        required: false
    entrypoint: ["/bin/sh", "-c"]
    command: ["go install github.com/air-verse/air@latest && air -c .air.toml"]
    networks:
      - 0p5dev
    env_file:
      - .env
    profiles:
      - dev
      - local

  postgres:
    image: postgres
    container_name: lfcont-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    profiles:
      - local
